// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AntInterface
{
	public class ChannelStatus
	{
		public const byte CHANNEL_STATE_MASK                  = 0x03;
		public const byte UNASSIGNED_CHANNEL                  = 0x00;
		public const byte ASSIGNED_CHANNEL                    = 0x01;
		public const byte SEARCHING_CHANNEL                   = 0x02;
		public const byte TRACKING_CHANNEL                    = 0x03;
	}
}

